apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ include "vyom-frontend-test.fullname" . }}-config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}