apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}-config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}