apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vyom-frontend-v2-ingress
  namespace: game-api # Ensure this matches the namespace where MinIO is deployed
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - vyom-v2.exkube.com
    secretName: vyom-frontend-v2-tls
  ingressClassName: nginx
  rules:
  - host: vyom-v2.exkube.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vyom-frontend-v2-service  # Replace with the name of your MinIO service
            port:
              number: 3000  # Ensure this matches the port on which MinIO is exposed

