apiVersion: v1
kind: Service
metadata:
  name: {{ include "furniture.fullname" . }}-service
  labels:
    {{- include "furniture.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "furniture.selectorLabels" . | nindent 4 }}
