apiVersion: v1
kind: Service
metadata:
  name: {{ include "vyom-frontend-test.fullname" . }}-service
  labels:
    {{- include "vyom-frontend-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vyom-frontend-test.selectorLabels" . | nindent 4 }}
