replicaCount: 1

image:
  repository: garagedev.azurecr.io/vyom-frontend
  pullPolicy: IfNotPresent
  tag: "0.0.5"

imagePullSecrets: []
nameOverride: "vyom-frontend"
fullnameOverride: ""

ingress: 
  enabled: true
  host: vyom.exsq.ai

service:
  port: 3010

resources: 
  requests:
    memory: "2Gi"
    cpu: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

serviceAccount:
  name: vyom-workload-identity-sa

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true

nodeSelector: {}

tolerations: {}

affinity: {}

config:
  BASE_URL: https://vyom-api.exkube.com
  CDN_ASSETS_BASE_URL: https://d7to0drpifvba.cloudfront.net/static
