replicaCount: 1

image:
  repository: registry.exkube.com/vyom-frontend-v2
  pullPolicy: IfNotPresent
  tag: "4260c19"

imagePullSecrets: []
nameOverride: "vyom-frontend-v2"
fullnameOverride: ""

ingress: 
  enabled: true
  host: vyom-v2.kubepipe.in

service:
  port: 3000

resources: 
  requests:
    memory: "64Mi"
    cpu: "250m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

serviceAccount:
  name: dafault

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: false

nodeSelector: {}

tolerations: {}

affinity: {}

config:
  BASE_URL: https://vyom-ml.kubepipe.in 
  CDN_ASSETS_BASE_URL: https://d7to0drpifvba.cloudfront.net/static
